apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gwapi-app-developer
  namespace: app-system-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gwapi-app-developer
subjects:
  - kind: User
    name: aldo
