apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwapi-app-developer
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["HTTPRoute", "GRPCRoute"]
    verbs: ["*"]
  - apiGroups: ["kuadrant.io"]
    resources: ["AuthPolicy", "RateLimitPolicy"]
    verbs: ["*"]
