apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwapi-cluster-operator
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes", "grpcroutes"]
    verbs: ["*"]
  - apiGroups: ["kuadrant.io"]
    resources: ["authpolicies", "ratelimitpolicies", "dnspolicies", "tlspolicies"]
    verbs: ["*"]
